# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
x_position_controller:
  type: effort_controllers/JointPositionController
  joint: x_mechanism_joint
  pid: {p: 1200, i: 20, d: 100}
y_position_controller:
  type: effort_controllers/JointPositionController
  joint: y_mechanism_joint
  pid: {p: 2000, i: 20, d: 50}
z_position_controller:
  type: effort_controllers/JointPositionController
  #joint: endeffector_base_link_joint
  joint: end_effector_joint
  pid: {p: 1000, i: 25, d: 150}
slider_position_controller:
  type: effort_controllers/JointPositionController
  joint: slider_joint
  pid: {p: 200, i: 10, d: 3}
mast_gripper_position_controller:
  type: effort_controllers/JointPositionController
  joint: mast_gripper_body_joint
  pid: {p: 20, i: 5, d: 3}
left_gripper_position_controller:
  type: effort_controllers/JointPositionController
  joint: mast_gripper_left_arm_joint
  pid: {p: 5, i: 1, d: 1}
right_gripper_position_controller:
  type: effort_controllers/JointPositionController
  joint: mast_gripper_right_arm_joint
  pid: {p: 5, i: 1, d: 1}
telescope_position_controller:
  type: effort_controllers/JointPositionController
  joint: telescope_joint
  pid: {p: 6, i: 1, d: 0.5}
lantenna_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_antenna_plate_joint
  pid: {p: 15, i: 1, d: 0.1}
rantenna_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_antenna_plate_joint
  pid: {p: 15, i: 1, d: 0.1}
servo_position_controller:
  type: velocity_controllers/JointVelocityController
  joint: servo_joint

#telescope_position_controller:
#  type: effort_controllers/JointPositionController
#  joint: telescope_joint
#  pid: {p: 1500, i: 10, d: 120}
